# Generated by Django 5.2.8 on 2025-11-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='city_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='City (EN)'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='city_ua',
            field=models.CharField(blank=True, max_length=100, verbose_name='Місто (UA)'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
