# Generated by Django 5.0.14 on 2026-03-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_gallery_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-created_at'], 'verbose_name': 'Gallery', 'verbose_name_plural': 'Galleries'},
        ),
        migrations.AddField(
            model_name='gallery',
            name='address',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Адреса'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='artists',
            field=models.TextField(blank=True, default='', help_text='Список митців (кожен з нового рядка)', verbose_name='Митці'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Місто'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='curators',
            field=models.TextField(blank=True, default='', verbose_name='Куратори'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Повний опис'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='founders',
            field=models.TextField(blank=True, default='', verbose_name='Засновники'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='founding_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Рік заснування'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='short_description',
            field=models.TextField(blank=True, default='', verbose_name='Короткий опис'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(default='temp-slug', help_text='Унікальний ідентифікатор для URL (наприклад: mystetskyi-arsenal)', max_length=200, unique=True, verbose_name='URL-slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='social_links',
            field=models.JSONField(blank=True, default=list, help_text='Список посилань, наприклад: [{"name": "Instagram", "url": "https://..."}]', verbose_name='Соціальні мережі'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='website_url',
            field=models.URLField(blank=True, default='', verbose_name='Вебсайт'),
        ),
    ]
