# Generated by Django 5.0.14 on 2026-04-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_gallery_options_gallery_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='address',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='artists',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='city',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='curators',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='description',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='founders',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='short_description',
        ),
        migrations.AddField(
            model_name='gallery',
            name='address_en',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Адреса (EN)'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='address_ua',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Адреса (UA)'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='artists_en',
            field=models.TextField(blank=True, default='', help_text='Список митців (кожен з нового рядка)', verbose_name='Митці (EN)'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='artists_ua',
            field=models.TextField(blank=True, default='', help_text='Список митців (кожен з нового рядка)', verbose_name='Митці (UA)'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='city_en',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Місто (EN)'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='city_ua',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Місто (UA)'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='curators_en',
            field=models.TextField(blank=True, default='', verbose_name='Куратори (EN)'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='curators_ua',
            field=models.TextField(blank=True, default='', verbose_name='Куратори (UA)'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Повний опис (EN)'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='description_ua',
            field=models.TextField(blank=True, default='', verbose_name='Повний опис (UA)'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='founders_en',
            field=models.TextField(blank=True, default='', verbose_name='Засновники (EN)'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='founders_ua',
            field=models.TextField(blank=True, default='', verbose_name='Засновники (UA)'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='short_description_en',
            field=models.TextField(blank=True, default='', verbose_name='Короткий опис (EN)'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='short_description_ua',
            field=models.TextField(blank=True, default='', verbose_name='Короткий опис (UA)'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус (активна?)'),
        ),
    ]
