# Generated by Django 5.0.14 on 2026-04-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_gallery_address_remove_gallery_artists_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='specialization_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Спеціалізація (EN)'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='specialization_ua',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Спеціалізація (UA)'),
        ),
    ]
