# Generated by Django 5.0.14 on 2026-04-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_favoritegallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Довгота'),
        ),
    ]
