# Generated by Django 5.2.8 on 2026-04-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_gallery_latitude_gallery_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='contentful_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Contentful ID'),
        ),
    ]
