# Generated by Django 5.2.8 on 2026-06-07 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_exhibition'),
    ]

    operations = [

        migrations.AddField(
            model_name='exhibition',
            name='source_url',
            field=models.URLField(blank=True, default='', help_text='Пряме посилання на підсторінку виставки (якщо є)', verbose_name='URL сторінки виставки'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='instagram_username',
            field=models.CharField(blank=True, default='', help_text='Наприклад: zag.gallery (без @). Якщо порожньо — витягується з monitoring_url', max_length=100, verbose_name='Instagram username'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='needs_js',
            field=models.BooleanField(default=False, help_text='Увімкни для SPA-сайтів (React/Vue без SSR), де звичайний requests повертає порожню сторінку', verbose_name='Потребує JS-рендерингу'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='last_scraped_hash',
            field=models.CharField(blank=True, default='', help_text='Хеш головної сторінки. Для підсторінок виставок — див. ExhibitionPage', max_length=255, verbose_name='Хеш останнього сканування'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='monitoring_url',
            field=models.URLField(blank=True, default='', help_text='Посилання на головну сторінку сайту, Instagram або Facebook для парсингу подій', verbose_name='URL для моніторингу'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='source_type',
            field=models.CharField(blank=True, default='website', help_text='website | instagram | facebook | telegram', max_length=50, verbose_name='Тип джерела'),
        ),
        migrations.CreateModel(
            name='ExhibitionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True, verbose_name='URL підсторінки виставки')),
                ('last_hash', models.CharField(blank=True, default='', max_length=32, verbose_name='MD5 хеш останнього сканування')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Час останнього сканування')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_pages', to='app.gallery', verbose_name='Галерея')),
            ],
            options={
                'verbose_name': 'Сторінка виставки',
                'verbose_name_plural': 'Сторінки виставок',
                'db_table': 'exhibition_page',
            },
        ),
    ]
