# Generated by Django 5.2.8 on 2026-06-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_gallery_contentful_id_exhibition_source_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='Пряме посилання на зображення постера або роботи з виставки', verbose_name='URL головного фото'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='contentful_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
