# Generated by Django 5.2.8 on 2026-06-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_gallery_needs_js'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='needs_js',
            field=models.BooleanField(default=False, help_text='Увімкни для SPA-сайтів (React/Vue без SSR), де звичайний requests повертає порожню сторінку', verbose_name='Потребує JS-рендерингу'),
        ),
    ]
