# Generated by Django 5.2.8 on 2025-11-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ua', models.CharField(max_length=200, verbose_name='Назва (UA)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Name (EN)')),
                ('description_ua', models.TextField(blank=True, verbose_name='Опис (UA)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (EN)')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Зображення')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Посилання')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
                'db_table': 'public_gallery',
            },
        ),
    ]
