# Generated by Django 5.0.14 on 2026-01-05 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_gallery_city_en_gallery_city_ua_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='city_en',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='city_ua',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='description_ua',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='url',
        ),
    ]
