# Generated by Django 5.0.14 on 2026-01-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_gallery_city_en_remove_gallery_city_ua_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='Зображення'),
        ),
    ]
