# Generated by Django 5.0.14 on 2026-01-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_favoritegallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritegallery',
            options={'verbose_name': 'Улюблена галерея', 'verbose_name_plural': 'Улюблені галереї'},
        ),
        migrations.AlterField(
            model_name='favoritegallery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Додано'),
        ),
        migrations.AlterModelTable(
            name='favoritegallery',
            table='favorite_gallery',
        ),
    ]
