# Generated by Django 5.0.14 on 2026-01-28 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_favoritegallery_options_and_more'),
        ('app', '0007_fix_favorite_gallery_table'),
    ]

    operations = [
    ]
